### ISSUE TITLE
Support Unmarshal too

### ISSUE THREAD

**Issue by tom10271** [liip/sheriff#13]
It is great to see people actually realize we need something work like sheriff in Golang's world.

As a Symfony developer too I enjoy JMSSerializationBundle very much on serializing and deserializing data easily.

It would be great if it can be supported too.

**Comment by mweibel** [comment]
Why can't you just use standard json unmarshalling using `json.Unmarshal` or so?

**Comment by tom10271** [comment]
The problem is I want to allow certain fields be able to deserialize into my struct only according to serialization group of the route.

For example, `/admin/orders/1` is allowed to deserialize orderTotal but not `/orders/1`. The standard library is not applicable.

**Comment by mweibel** [comment]
This is not planned currently.
