### ISSUE TITLE
[Feature request] Add option to add fields without 'groups' tag by default

### ISSUE THREAD

**Issue by lmindwarel** [liip/sheriff#23]
Hi,

First, thank for this library, very helpful for me.

I use sheriff in a project with big struct, with many fields. So it is not very practical to add the `groups` tag on fields on by one.

Can you provide a way to automatically add field without `groups` tag ? For exemple, an attribute `addFieldsWithoutGroups` in `shriff.Options`

Thanks !

**Comment by mweibel** [comment]
would #10 help you there?

**Comment by mweibel** [comment]
also #17 has been merged recently - does that help in your case maybe?

**Comment by lmindwarel** [comment]
OK thanks I didn't see that
