### ISSUE TITLE
nil array handling

### ISSUE THREAD

**Issue by TorbenCK** [liip/sheriff#39]
https://github.com/liip/sheriff/blob/cd01545943c98e7e98650619711d087b965d9529/sheriff.go#L237

sheriff sets all nil arrays to empty array. To avoid this the following code should be added before v.Len()

if v.IsNil() {
	return val, nil
}

**Comment by mweibel** [comment]
thanks for the report!

it'd be great if you could submit a PR + add a test :+1:

**Comment by TorbenCK** [comment]
https://github.com/liip/sheriff/pull/40/files done ;)

**Comment by mweibel** [comment]
fixed by #40 - thanks!
